name: Changelog

on:
  pull_request:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check Changelog Updated
      id: checkchangelogupdated
      if: ${{ contains( github.event.pull_request.labels.*.name, 'no-changelog') != true }}
      uses: t1m0thyj/check_changelog_action@lerna-update
      with:
        header: '## Recent Changes'
        file: 'CHANGELOG.md'
        token: ${{ secrets.GITHUB_TOKEN }}
        lerna: true
